### ISSUE TITLE
Difference between this and bredis

### ISSUE THREAD

**Issue by stephendliang** [hamidr/async-redis#23]
I was wondering if there is any difference between bredis (also an async redis client) and this?

**Comment by hamidr** [comment]
Being honest... It seems it is more complicated than this project but with more features. I really like it though.
By taking a look at my code base you can tell it's just a simple client library.
If you are looking for more patterns than callback based event handling then I guess bredis is your friend.
But async-redis gets the job done sooner I assume.

The very first reason behind development of this code base was adaptability with "libevpp".
I had a legacy code base which I couldn't do anything unless write client around it. So there you go!
