### ISSUE TITLE
Alternative Redis client proposed for inclusion in Boost

### ISSUE THREAD

**Issue by mzimbres** [hamidr/async-redis#25]
Sorry for opening an issue for this, I did not find any better means of contacting you.

I would like to invite your community to write a review for an alternative Redis client library that is being proposed for inclusion in Boost. As the author of a Redis client yourself your opinion would be highly valuable. For more information see https://lists.boost.org/Archives/boost/2023/01/253871.php.

Thanks

**Comment by hamidr** [comment]
You have my support.
I've retired my library in favor of boost-redis.
https://github.com/hamidr/async-redis/commit/4628a994dfd337c0df9cf023b45a6b331bd0a6b7

**Comment by klemens-morgenstern** [comment]
This has to be the highest compliment a library author can receive.

**Comment by mzimbres** [comment]
@hamidr wow many thanks for that support. Boost.Redis has a channel (boost-redis) in the cpplang slack https://cppalliance.org/slack/. Consider joining it, it would be great to have you there helping shape the future of Boost.Redis.
